import React from "react";
import { AiOutlineTable, AiOutlineCode } from "react-icons/ai";

const WordEditorItems = ({ editor }) => {
  if (!editor) {
    return [];
  }
  return [
    // {
    //   key: "undo",
    //   TooltipTitle: "undo",
    //   label: "Undo",
    //   icon: <i className="ri-arrow-go-back-fill " />,
    //   onClick: () => editor.chain().focus().undo().run(),
    //   isActive: () => editor.isActive("bold"),
    //   canExecute: () => editor.can().chain().focus().undo().run(),
    //   size: "md",
    //   type: "text",
    //   group: "options",
    // },
    // {
    //   key: "redo",
    //   TooltipTitle: "redo",
    //   label: "Redo",
    //   icon: <i className="ri-arrow-go-forward-fill" />,
    //   onClick: () => editor.chain().focus().redo().run(),
    //   isActive: () => editor.isActive("bold"),
    //   canExecute: () => editor.can().chain().focus().redo().run(),
    //   size: "md",
    //   type: "text",
    //   group: "options",
    // },
    {
      key: "bold",
      TooltipTitle: "Bold",
      label: "Bold",
      icon: <i className="ri-bold" />,
      onClick: () => editor.chain().focus().toggleBold().run(),
      isActive: () => editor.isActive("bold"),
      canExecute: () => editor.can().chain().focus().toggleBold().run(),
      size: "md",
      type: "text",
      group: "textFormatting",
    },
    {
      key: "italic",
      TooltipTitle: "Italic",
      label: "Italic",
      icon: <i className="ri-italic" />,
      onClick: () => editor.chain().focus().toggleItalic().run(),
      isActive: () => editor.isActive("italic"),
      canExecute: () => editor.can().chain().focus().toggleItalic().run(),
      size: "md",
      type: "text",
      group: "textFormatting",
    },
    {
      key: "strike",
      TooltipTitle: "Strike",
      label: "Strike",
      icon: <i className="ri-strikethrough" />,
      onClick: () => editor.chain().focus().toggleStrike().run(),
      isActive: () => editor.isActive("strike"),
      canExecute: () => editor.can().chain().focus().toggleStrike().run(),
      size: "md",
      type: "text",
      group: "textFormatting",
    },

    {
      key: "code",
      TooltipTitle: "Code",
      label: "Code",
      icon: <i className="ri-code-view" />,
      onClick: () => editor.chain().focus().toggleCode().run(),
      isActive: () => editor.isActive("code"),
      canExecute: () => editor.can().chain().focus().toggleCode().run(),
      size: "md",
      type: "text",
      group: "textFormatting",
    },
    {
      key: "paragraph",
      TooltipTitle: "Paragraph",
      label: "Paragraph",
      icon: <i className="ri-paragraph" />,
      onClick: () => editor.chain().focus().setParagraph().run(),
      isActive: () => editor.isActive("paragraph"),
      canExecute: null,
      size: "md",
      type: "text",
      group: "textFormatting",
    },
    {
      key: "bulletList",
      TooltipTitle: "Bullet List",
      label: "Bullet List",
      icon: <i className="ri-list-check" />,
      onClick: () => editor.chain().focus().toggleBulletList().run(),
      isActive: () => editor.isActive("bulletList"),
      canExecute: null,
      size: "md",
      type: "text",
      group: "ListFormatting",
    },
    {
      key: "orderedList",
      TooltipTitle: "Align left",
      label: "Number List",
      icon: <i className="ri-list-ordered" />,
      onClick: () => editor.chain().focus().toggleOrderedList().run(),
      isActive: () => editor.isActive("orderedList"),
      canExecute: null,
      size: "md",
      type: "text",
      group: "ListFormatting",
    },
    {
      key: "alignLeft",
      TooltipTitle: "Align left",
      label: "Align left",
      icon: <i className="ri-align-left" />,
      onClick: () => editor.chain().focus().setTextAlign("left").run(),
      isActive: () => editor.isActive({ textAlign: "left" }),
      canExecute: () => editor.can().chain().focus().setTextAlign("left").run(),
      size: "md",
      type: "text",
      group: "textAlignment",
    },

    {
      key: "alignCenter",
      TooltipTitle: "Align center",
      label: "Align center",
      icon: <i className="ri-align-center" />,
      onClick: () => editor.chain().focus().setTextAlign("center").run(),
      isActive: () => editor.isActive({ textAlign: "center" }),
      canExecute: () =>
        editor.can().chain().focus().setTextAlign("center").run(),
      size: "md",
      type: "text",
      group: "textAlignment",
    },
    {
      key: "alignRight",
      TooltipTitle: "Align right",
      label: "Align right",
      icon: <i className="ri-align-right" />,
      onClick: () => editor.chain().focus().setTextAlign("right").run(),
      isActive: () => editor.isActive({ textAlign: "right" }),
      canExecute: () =>
        editor.can().chain().focus().setTextAlign("right").run(),
      size: "md",
      type: "text",
      group: "textAlignment",
    },
    {
      key: "alignJustify",
      TooltipTitle: "Align justify",
      label: "Align justify",
      icon: <i className="ri-align-justify" />,
      onClick: () => editor.chain().focus().setTextAlign("justify").run(),
      isActive: () => editor.isActive({ textAlign: "justify" }),
      canExecute: () =>
        editor.can().chain().focus().setTextAlign("justify").run(),
      size: "md",
      type: "text",
      group: "textAlignment",
    },
    {
      key: "quote",
      TooltipTitle: "Quote",
      label: "Quote",
      icon: <i className="ri-quote-text" />,
      onClick: () => editor.chain().focus().toggleBlockquote().run(),
      isActive: () => editor.isActive("blockquote"),
      canExecute: () => editor.can().chain().focus().toggleBlockquote().run(),
      size: "md",
      type: "text",
      group: "textAlignment",
    },
    {
      key: "highlight",
      TooltipTitle: "Highlight",
      label: "Highlight",
      icon: <i className="ri-mark-pen-fill" />,
      onClick: () => editor.chain().focus().toggleHighlight().run(),
      isActive: () => editor.isActive("highlight"),
      canExecute: () => editor.can().chain().focus().toggleHighlight().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "removeMarks",
      TooltipTitle: "Remove Marks",
      label: "Remove Marks",
      icon: <i className="ri-format-clear" />,
      onClick: () => editor.chain().focus().unsetAllMarks().run(),
      isActive: () => editor.isActive("allMarks"),
      canExecute: () => editor.can().chain().focus().unsetAllMarks().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "removeAllEffects",
      TooltipTitle: "Remove All Effect",
      label: "Remove All Effect",
      icon: <i className="ri-eraser-line" />,
      onClick: () => editor.chain().focus().clearNodes().run(),
      isActive: () => editor.isActive("clearNodes"),
      canExecute: () => editor.can().chain().focus().clearNodes().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "codeBlock",
      TooltipTitle: "Code Block",
      label: "Code Block",
      icon: <AiOutlineCode />,
      onClick: () => editor.chain().focus().toggleCodeBlock().run(),
      isActive: () => editor.isActive("codeBlock"),
      canExecute: () => editor.can().chain().focus().toggleCodeBlock().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "insertLine",
      TooltipTitle: "Add Line under",
      label: "Add Line under",
      icon: <i className="ri-separator" />,
      onClick: () => editor.chain().focus().setHorizontalRule().run(),
      isActive: () => editor.isActive("horizontalRule"),
      canExecute: () => editor.can().chain().focus().setHorizontalRule().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "hardBreak",
      TooltipTitle: "Break Enter",
      label: "Break Enter",
      icon: <i className="ri-corner-down-left-fill" />,
      onClick: () => editor.chain().focus().setHardBreak().run(),
      isActive: () => editor.isActive("hardBreak"),
      canExecute: () => editor.can().chain().focus().setHardBreak().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
    {
      key: "insertTable",
      TooltipTitle: "Insert Table",
      label: "Insert Table",
      icon: <AiOutlineTable />,
      onClick: () =>
        editor
          .chain()
          .focus()
          .insertTable({ rows: 3, cols: 3, withHeaderRow: true })
          .run(),
      isActive: () => editor.isActive("table"),
      canExecute: () => editor.can().chain().focus().insertTable().run(),
      size: "md",
      type: "text",
      group: "additionalFormatting",
    },
  ];
};

export default WordEditorItems;
